apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ax8ndqenq-nodejs 
  janus-idp.io/tekton: ax8ndqenq-nodejs
  backstage.io/kubernetes-id: ax8ndqenq-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ax8ndqenq-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  