apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ax8ndqenq-nodejs
  janus-idp.io/tekton: ax8ndqenq-nodejs
  backstage.io/kubernetes-id: ax8ndqenq-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ax8ndqenq-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
